# Generated by Django 4.2 on 2025-04-22 07:57

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[website.validators.validate_iranian_cellphone_number]),
        ),
    ]
