# Generated by Django 4.2.20 on 2025-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productimagemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='avg_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
