# Generated by Django 4.2.20 on 2025-04-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rate',
        ),
    ]
