# Generated by Django 4.2.20 on 2025-05-05 08:58

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productcategorymodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
