# Generated by Django 4.2.21 on 2025-05-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
