# Generated by Django 4.2.20 on 2025-05-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='order_id',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='authority_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار'), (2, 'پرداخت موفق'), (3, 'پرداخت ناموفق')], default=1),
        ),
    ]
